### ISSUE TITLE
Event name not respected, type tracked instead

### ISSUE THREAD

**Issue by agcty** [mountainash/posthog-managed-component#12]
**Current behaviour**
Currently, when you track an event, the name that shows up in the posthog dashboard will always be "event" which doesn't make sense.

<img width="1231" alt="image" src="https://github.com/mountainash/posthog-managed-component/assets/12101091/86e8ef65-4923-4402-a8fd-a6d20b23175e">

**Expected behaviour**
Instead of the type that is now used as the event name, the actual event name should be used as described in the docs: https://posthog.com/tutorials/api-capture-events

Then you'll also be able to see the correct event name in the ph dashboard:
<img width="1213" alt="image" src="https://github.com/mountainash/posthog-managed-component/assets/12101091/ad57115f-1fcd-4422-b005-9f8378f95111">

I have created a PR that fixes this: https://github.com/mountainash/posthog-managed-component/pull/11

**Comment by mountainash** [comment]
This was fixed in ef6a8ebe99f77d6b5bb7436feeb0c8e4c31b4769 ready for the next version release. Thanks for reporting it.
