### ISSUE TITLE
Identify not working as expected

### ISSUE THREAD

**Issue by agcty** [mountainash/posthog-managed-component#13]
The identify functionality of the mc does not work as expected having the effect that you can't connect anonymous distinct ids to an id known by your app. Essentially, identify doesn't work at all at the moment.

I am not entirely sure that sending an $identify event event works (according to the docs)
<img width="614" alt="image" src="https://github.com/mountainash/posthog-managed-component/assets/12101091/9a706fce-bbaa-4d6c-85d5-5775f7f53b44">

However, I tried reverse engineering the posthog-js library's identify functionality and it seems that you can in fact actually use the $identify event but currently the mc does not send the right values.

Seems like you need to send at least these fields:

distinct_id -> the new id that you want to set
$anon_distinct_id -> the id that the user had previously (should be sent in the properties object

both need to be sent at the top level, not in the properties object.

with some small adaptions it should work though.

The mc would have to get the current distinct id of the request and send it as the anonymous id and take in a parameter distinct_id.

**Comment by mountainash** [comment]
Thank you for looking into this in depth. If you are able to make a PR to handle these changes that would be really helpful.

**Comment by mountainash** [comment]
Where did you learn about `$anon_distinct_id`? I don't see this anywhere in the documentation.
